### ISSUE TITLE
Copyright notice: One of your dependencies has violated copyright law

### ISSUE THREAD

**Issue by acheong08** [yxKryptonite/chatgpt-qqbot#1]
https://github.com/labteral/chatgpt-python/issues/7#issue-1484782172

**Comment by yxKryptonite** [comment]
fixed.

see [commit](https://github.com/yxKryptonite/chatgpt-qqbot/commit/39d0e55ccdb689f5c87614439e941616e7c5bef4)

if it's okay, respond it and I will close the issue
