### ISSUE TITLE
没有任何效果

### ISSUE THREAD

**Issue by chenyv118** [yxKryptonite/chatgpt-qqbot#2]
![image](https://user-images.githubusercontent.com/92171340/209160045-5fb5dc51-e670-4d53-9cb3-97740b032b9f.png)
并没有任何回复
![image](https://user-images.githubusercontent.com/92171340/209160199-4912f6c3-6eee-4e2e-bbc7-45f6cc2b554e.png)

**Comment by yxKryptonite** [comment]
看我最新 commit 的版本

另外，你的使用方式是错的，你可以先对机器人发送 `/help` 查看所有功能。所有内置功能均以 `/` 开头。

**Comment by chenyv118** [comment]
> 看我最新 commit 的版本
> 
> 另外，你的使用方式是错的，你可以先对机器人发送 `/help` 查看所有功能。所有内置功能均以 `/` 开头。

是的没错，需要用`/`才能正常使用，但是在使用的过程中提示“服务出现问题，请稍后再试”。
错误信息：
 cause: Error: unexpected end of file
      at BrotliDecoder.zlibOnError [as onerror] (node:zlib:189:17) {
    errno: -5,
    code: 'Z_BUF_ERROR'
  }
是为什么呢？

如图：
![image](https://user-images.githubusercontent.com/92171340/209275270-89afea2b-9b71-4b91-99eb-ba5ba0cad5fd.png)

**Comment by yxKryptonite** [comment]
你是按照最新的 `README.md` 进行操作的吗？如果是的话，可以再把你的问题描述得更清楚一点吗？

**Comment by chenyv118** [comment]
> 你是按照最新的 `README.md` 进行操作的吗？如果是的话，可以再把你的问题描述得更清楚一点吗？

命令`/help`和`/translate`都可用，但是使用`/chatgpt`和`/draw`命令的时候就会出现这样的情况：
![image](https://user-images.githubusercontent.com/92171340/209280975-50150279-2da7-4184-ac8c-9fc1379b24a5.png)

错误信息如下：
![image](https://user-images.githubusercontent.com/92171340/209281793-5869b040-994c-4d9b-9e02-263dfe355847.png)
请问是因为session-token或Dalle2Token配置错误的原因嘛?
配置如下：
![image](https://user-images.githubusercontent.com/92171340/209282064-5672a9c7-7f5e-47cd-a1a4-d6e08683ee0a.png)

**Comment by yxKryptonite** [comment]
请看[这里](https://github.com/yxKryptonite/chatgpt-qqbot#usage)。由于 openai 新增了人机验证，现在 chatgpt 不能用 session token 登陆了，而是要人工手动通过人机验证，你需要填入 openai 的账号和密码。

请 pull 最新的 repo ，然后根据 `README.md` 进行操作。

**Comment by yxKryptonite** [comment]
如果还是不行，建议删除文件夹从头开始。

另外，dalle2的token应该以 `sess-` 开头，你可能弄错了
